### ISSUE TITLE
underscore-plus error 

### ISSUE THREAD

**Issue by sujato** [SamaneriVimala/velthuis-autocorrect#1]
With the updated files, I replaced both folders, and got the following error:

Failed to activate the autocorrect package
Cannot find module 'underscore-plus'
Hide Stack Trace
Error: Cannot find module 'underscore-plus'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:354:58)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:40:43)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/user/.atom/packages/atom-autocorrect/lib/AutoCorrectView.js:4:11)
    at Object.<anonymous> (/home/user/.atom/packages/atom-autocorrect/lib/AutoCorrectView.js:231:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/user/.atom/packages/atom-autocorrect/lib/AutoCorrectPlugin.js:4:27)
    at Object.<anonymous> (/home/user/.atom/packages/atom-autocorrect/lib/AutoCorrectPlugin.js:50:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/user/.atom/packages/atom-autocorrect/lib/index.js:3:29)
    at Object.<anonymous> (/home/user/.atom/packages/a

**Comment by SamaneriVimala** [comment]
underscore node module added
